name: Metrics
on:
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Menggunakan Secret Token kamu
          token: ${{ secrets.METRICS_TOKEN }}

          user: AKHDIYAN
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          # Opsi yang VALID untuk menarik data repo private & collaborator
          repositories_affiliations: owner, collaborator, organization_member

          # Kalender Kontribusi 3D (Isocalendar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Bahasa Pemrograman
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage

          plugin_music: no
